### ISSUE TITLE
Hosting on Kubernetes

### ISSUE THREAD

**Issue by cookiem3r** [j4ym0/pia-qbittorrent-docker#17]
I am trying to host the container on Kubernetes. I got the deployment working with the deployment ymal below. I verify the container to be running after looking at the log of the container.

```apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbtorrent-deployment
  labels:
    app: qbtorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbtorrent
  template:
    metadata:
      labels:
        app: qbtorrent
    spec:
      containers:
      - name: qbtorrent
        image: j4ym0/pia-qbittorrent:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - mountPath: /downloads
          name: data-volume
        ports:
        - containerPort: 8888
        env:
        - name: REGION
          value: "xxxxx"
        - name: USER
          value: "xxxxx"
        - name: PASSWORD
          value: "xxxxx"
      volumes:
      - name: data-volume
        hostPath:
         path: /home/xxx/Projects/torrent
         type: Directory
```

However, I can't seem to get the networking right. I created a simple NodePort to try to get the UI accessible from outside, but I just get "Unauthorized"

```apiVersion: v1
kind: Service
metadata:
  name: qbtorrent-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8888
      nodePort: 30008
  selector:
    app: qbtorrent
```

Any tips to point me in the right direction?

**Comment by j4ym0** [comment]
Not Familiar with Kubernetes.

1. You may want to map a directory for /config so your config and torrents resume after updates/restarts/recreates
2. I believe the port in the service should be 8888

looks like qbittorrent is blocking access to the WebUI as it is coming from the wrong port (30008)
Having never use it before i spun up a linux VM and was able to replicate and fix with `kubectl -- exec <POD> --  sh -c 'echo "WebUI\HostHeaderValidation=false" >> /config/qBittorrent/config/qBittorrent.conf'`

**Comment by cookiem3r** [comment]
```
xxx@yyy:~/Projects/kubernetes$ kubectl exec qbtorrent-deployment-5945447f94-2k4gd -- sh -c 'echo "WebUI\HostHeaderValidation=false" >> /config/qBittorrent/config/qBittorrent.conf'
xxx@yyy:~/Projects/kubernetes$ kubectl exec qbtorrent-deployment-5945447f94-2k4gd -- cat -- /config/qBittorrent/config/qBittorrent.conf
[AutoRun]
enabled=false
program=

[BitTorrent]
Session\DefaultSavePath=/downloads/
Session\Port=23750
Session\QueueingSystemEnabled=true
Session\TempPath=/downloads/temp/

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=6

[Network]
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/temp/
WebUI\Address=*
WebUI\Port=8888
WebUI\ServerDomains=*
WebUI\SessionTimeout=3600
WebUI\UseUPnP=true
WebUI\Username=admin
WebUI\HostHeaderValidation=false
```

Managed to edit the config file in the pod but doesn't seem to work. Is there a command to restart the service or something like that?

**Comment by cookiem3r** [comment]
Alright I got it working. I mapped a volume that points to /config and deployed it once to get the current configs. I then delete the deployment, add WebUI\HostHeaderValidation=false into qBittorrent.conf and deployed it again.

Complete deployment file here.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbtorrent-deployment
  labels:
    app: qbtorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbtorrent
  template:
    metadata:
      labels:
        app: qbtorrent
    spec:
      containers:
      - image: j4ym0/pia-qbittorrent:latest
        name: qbtorrent
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - mountPath: /downloads
          name: data-volume
        - mountPath: /config/qBittorrent/config/
          name: config-volume
        ports:
        - containerPort: 8888
        env:
        - name: REGION
          value: "Singapore"
        - name: USER
          value: "p3463649"
        - name: PASSWORD
          value: "Pia@8805693"
      volumes:
      - name: data-volume
        hostPath:
         path: /home/rui/Projects/torrent
         type: Directory
      - name: config-volume
        hostPath:
          path: /home/rui/Projects/config
          type: Directory
```

I must add that it is not downloading anything yet. I believe more configuration is needed at the service level to allow UDP connections.
