### ISSUE TITLE
Container Loops After "Exiting With Code 0" Right After Connecting To VPN

### ISSUE THREAD

**Issue by nafzib** [j4ym0/pia-qbittorrent-docker#33]
I have a similar issue to one another user had in here, but they were able to solve theirs; at first my container was just hanging at the "Waiting for VPN to connect" step and never doing anything else. But in looking around online, and trying some stuff out, I found that if I added "privileged: true" to my compose yml, it would go just slightly past that step. Unfortunately, after connecting to the VPN, it just "exits" and then loops, starting over endlessly.

```
qbittorrent-pia  |  =========================================
qbittorrent-pia  |  OS: Alpine Linux v3.20
qbittorrent-pia  |  =========================================
qbittorrent-pia  |  OpenVPN version: 2.6.11
qbittorrent-pia  |  Iptables version: v1.8.10
qbittorrent-pia  |  qBittorrent version: v5.0.2
qbittorrent-pia  |  =========================================
qbittorrent-pia  | 
qbittorrent-pia  | System parameters:
qbittorrent-pia  |  * userID: 1000
qbittorrent-pia  |  * groupID: 1000
qbittorrent-pia  |  * timezone: CST -0600
qbittorrent-pia  | OpenVPN parameters:
qbittorrent-pia  |  * Region: us_chicago
qbittorrent-pia  | Local network parameters:
qbittorrent-pia  |  * Web UI port: 8888
qbittorrent-pia  |  * Adding PIA DNS Servers
qbittorrent-pia  |  * * Adding 84.200.69.80 to resolv.conf
qbittorrent-pia  |  * * Adding 84.200.70.40 to resolv.conf
qbittorrent-pia  |  * * Adding 103.196.38.38 to resolv.conf
qbittorrent-pia  |  * * Adding 103.196.38.39 to resolv.conf
qbittorrent-pia  | [INFO] /auth.conf already exists
qbittorrent-pia  | [INFO] Clearing environment variables USER and PASSWORD...DONE
qbittorrent-pia  | [INFO] Reading OpenVPN configuration...
qbittorrent-pia  |  * Port: 1198
qbittorrent-pia  |  * Domain: us-chicago.privacy.network
qbittorrent-pia  | [INFO] Detecting IP addresses corresponding to us-chicago.privacy.network...
qbittorrent-pia  |    212.102.59.219
qbittorrent-pia  |    212.102.59.156
qbittorrent-pia  |    181.214.164.50
qbittorrent-pia  | [INFO] Creating target OpenVPN files in /openvpn/target...DONE
qbittorrent-pia  | [INFO] Finding network properties...
qbittorrent-pia  |  * Detecting default gateway...172.18.0.1
qbittorrent-pia  |  * Detecting local interface...eth0
qbittorrent-pia  |  * Detecting local subnet...172.18.0.0/16
qbittorrent-pia  |  * Detecting target VPN interface...tun0
qbittorrent-pia  | [INFO] Checking firewall
qbittorrent-pia  |  * Current mode: Normal (nftables)
qbittorrent-pia  |  * iptables set to prefered
qbittorrent-pia  | [INFO] Setting firewall
qbittorrent-pia  |  * Blocking everything
qbittorrent-pia  |    * Deleting all iptables rules...DONE
qbittorrent-pia  |    * Block input traffic...DONE
qbittorrent-pia  |    * Block output traffic...DONE
qbittorrent-pia  |    * Block forward traffic...DONE
qbittorrent-pia  |  * Creating general rules
qbittorrent-pia  |    * Accept established and related input and output traffic...DONE
qbittorrent-pia  |    * Accept local loopback input and output traffic...DONE
qbittorrent-pia  |    * Accept traffic to webui-port:8888...DONE
qbittorrent-pia  |  * Creating VPN rules
qbittorrent-pia  |    * Accept output traffic to VPN server 212.102.59.219 through eth0, port udp 1198...DONE
qbittorrent-pia  |    * Accept output traffic to VPN server 212.102.59.156 through eth0, port udp 1198...DONE
qbittorrent-pia  |    * Accept output traffic to VPN server 181.214.164.50 through eth0, port udp 1198...DONE
qbittorrent-pia  |    * Accept all output traffic through tun0...DONE
qbittorrent-pia  |  * Creating local subnet rules
qbittorrent-pia  |    * Accept input and output traffic to and from 172.18.0.0/16...DONE
qbittorrent-pia  | [INFO] Launching OpenVPN
qbittorrent-pia  | [INFO] Checking qBittorrent config
qbittorrent-pia  | [INFO] Waiting for VPN to connect
qbittorrent-pia  | [INFO] Setting up port forwarding
qbittorrent-pia  |  * Got PIA token
qbittorrent-pia  |  * Got PIA gateway 10.37.112.1
qbittorrent-pia exited with code 0
```

After this last line where it says "exited with code 0" it just starts over again, gets to the exact same point, then repeats endlessly. Here is my compose file:

```
services:
# QBittorrent + Private Internet Access VPN
  qbittorrent-pia:
    container_name: qbittorrent-pia
    image: j4ym0/pia-qbittorrent:latest
    restart: always
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 2g
        reservations:
          memory: 256m
    volumes:
      - '/containers/data:/data'
      - '/containers/configs/qbittorrent-pia:/config'
      - '/containers/data/torrents:/downloads'
    environment:
      - UID=1000
      - GID=1000
      - TZ=America/Chicago
      - REGION=us_chicago
      - USER=user
      - PASSWORD=pass
      - PORT_FORWARDING=true
      - WEBUI_PORT=8888
      - DNS_SERVERS=84.200.69.80,84.200.70.40,103.196.38.38,103.196.38.39
#    privileged: true <-- Adding this in got it one step farther than before, but causes it to loop somehow.
    ports:
      - '8888:8888'
```

I'm not sure if there are other logs somewhere I can look at, but I couldn't find any in my containers folder.
