### ISSUE TITLE
Synology issue

### ISSUE THREAD

**Issue by marc115uk** [j4ym0/pia-qbittorrent-docker#42]
This could be a me problem but have a stack in portainer that deploys pia-qbittorrent-docker, radarr, prowlarr, sonarr, overseerr. I am using sysnology DS920+.  I have been using the synology tag for quite some time. I noticed in version 5.0.0 looks like the issue with synology was fixed, so today I changed the tag to latest, when I redeployed the stack other the other services were deployed, and in container logs were showing as avaliable at localhost:respective ports. However I was unable to access them. Also have uptimekuma running and that was still showing them as down. I have reverted back to the synology tag and they are all back up and running. Was this issue not fixed or am I doing something wrong/missed another update somewhere? 
Many thanks 

```
services:
    pia-qbittorrent:
        image: j4ym0/pia-qbittorrent:synology
        container_name: pia-qbittorrent
        cap_add:
            - NET_ADMIN
        environment:
            - REGION=UK_London
            - USER=*****
            - PASSWORD=*****
            - LEGACY_IPTABLES=true

        volumes:
            - /volume1/docker/pia:/config
            - /volume1/Bigstorage/Users/Marc/Downloads/Torrent:/downloads
        ports:
            - "8888:8888"
            - "9696:9696"
            - "7878:7878"
            - "8989:8989"
            - "5055:5055"         
        restart: always       
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
          - PUID=1026
          - PGID=100
          - TZ=Europe/London
          - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sonarr
          - TP_COMMUNITY_THEME=true
          - TP_THEME=soul
          - TP_ADDON=sonarr-text-logo
        volumes:
          - /volume1/docker/sonarr:/config
          - /volume1/Bigstorage/Users/Marc/Plexmedia/TV:/tv #optional
          - /volume1/Bigstorage/Users/Marc/Downloads/Torrent:/downloads #optional
        network_mode: "service:pia-qbittorrent"  
        depends_on:
          pia-qbittorrent:
            condition: service_healthy
            restart: true
        restart: always     
    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
          - PUID=1026
          - PGID=100
          - TZ=Europe/London
          - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr
          - TP_COMMUNITY_THEME=true
          - TP_THEME=soul
        volumes:
          - /volume1/docker/radarr:/config
          - /volume1/Bigstorage/Users/Marc/Plexmedia/Movies:/movies #optional
          - /volume1/Bigstorage/Users/Marc/Downloads/Torrent:/downloads #optional
        network_mode: "service:pia-qbittorrent"  
        depends_on:
          pia-qbittorrent:
            condition: service_healthy
            restart: true        
        restart: always    
        
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
          - PUID=1026
          - PGID=100
          - TZ=Europe/London
          - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:prowlarr
          - TP_COMMUNITY_THEME=true
          - TP_THEME=soul
        volumes:
          - /volume1/docker/prowlarr:/config
        network_mode: "service:pia-qbittorrent"      
        depends_on:
          pia-qbittorrent:
            condition: service_healthy
            restart: true        
        restart: always    
        
    overseerr:
        image: lscr.io/linuxserver/overseerr:latest
        container_name: overseerr
        environment:
          - PUID=1026
          - PGID=100
          - TZ=Europe/London
        volumes:
          - /volume1/docker/overseerr:/config
        network_mode: "service:pia-qbittorrent" 
        depends_on:
          pia-qbittorrent:
            condition: service_healthy
            restart: true        
        restart: always        
 ```
